# Generated by Django 4.1 on 2022-08-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department", old_name="dedscription", new_name="description",
        ),
        migrations.AlterField(
            model_name="employee",
            name="alt_phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
