# Generated by Django 4.1 on 2022-08-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_rename_dedscription_department_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="benefits", options={"verbose_name_plural": "Benefits"},
        ),
        migrations.AlterField(
            model_name="payroll",
            name="end_date",
            field=models.DateField(blank=True, help_text="Payroll Date", null=True),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="start_date",
            field=models.DateField(help_text="Start Date of payroll", null=True),
        ),
    ]
