# Generated by Django 4.1 on 2022-08-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_alter_benefits_options_alter_payroll_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payroll",
            name="basic_salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="uif_contribution",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=7, null=True
            ),
        ),
    ]
