# Generated by Django 4.1 on 2022-08-29 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0006_alter_bankinfo_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="id_number",
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="passport",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="date_hired",
            field=models.DateField(
                blank=True, help_text="Employee hired date.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="designation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="designation",
                to="employee.designation",
            ),
        ),
    ]
