# Generated by Django 4.1 on 2022-08-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0007_employee_id_number_employee_passport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="pension_number",
            field=models.CharField(max_length=13, null=True),
        ),
    ]
