# Generated by Django 4.1 on 2022-08-26 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=150, null=True)),
                ("landline", models.CharField(blank=True, max_length=20)),
                ("phone", models.CharField(max_length=20, null=True)),
                ("address", models.TextField(null=True)),
                ("email", models.EmailField(max_length=150)),
                ("logo", models.ImageField(blank=True, upload_to="products/%Y/%m/%d")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="company_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
