# Generated by Django 4.1 on 2022-08-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company", options={"verbose_name_plural": "Company"},
        ),
    ]
