# Generated by Django 4.1 on 2022-08-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_alter_company_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(blank=True, upload_to="static/media/%Y/%m/%d"),
        ),
    ]
